language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t StalinMazaEpn/docker-react-smdev -f Dockerfile.dev .

script:
  - docker run -e CI=true StalinMazaEpn/docker-react-smdev npm run test